# Generated by Django 4.0.2 on 2022-02-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_director_description_alter_cinema_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Рецензии', 'verbose_name_plural': 'Рецензия'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Рецензия'),
        ),
    ]
