# Generated by Django 4.0.2 on 2022-02-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review_title_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
