# Generated by Django 4.0.2 on 2022-02-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.FloatField(null=True, verbose_name='Купить онлайн трансляцию'),
        ),
    ]
