# Generated by Django 4.0.2 on 2022-02-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price_с',
            field=models.FloatField(null=True, verbose_name='Стоимость билета'),
        ),
    ]
