# Generated by Django 4.0.2 on 2022-02-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movie_price_с'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='price_с',
            new_name='price_ticket',
        ),
    ]
